package:
  name: dyno
  version: "0.1.2"

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  always_include_files:
  - dyno/modfile_grammar.lark

source:
  path: ../

requirements:
  build:
    - python <3.12,>=3.10
    - poetry >=1.2

  run:
    - python <3.12,>=3.10
    - dolang
    - numpy
    - pandas
