package:
  name: dyno
  version: "0.1.7"

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  always_include_files:
  - dyno/dynsym/modfile_grammar.lark
  - dyno/dynsym/grammar.lark

source:
  path: ../

requirements:
  build:
    - python <3.14,>=3.12
    - poetry >=1.2

  run:
    - python <3.14,>=3.12
    - numpy
    - pandas
