[workspace]
authors = ["Pablo Winant <pablo.winant@gmail.com>","Ousema Bouaneni <ousema.bouaneni@polytechnique.edu>"]
description = "Macroeconomic model solver"
channels = ["conda-forge"]

preview = ["pixi-build"]
platforms = ["linux-64"]

[package]
name = "dyno"
version = "0.1.7.1"

[pypi-dependencies]
dyno = { path = "." , editable = true}

[dependencies]
python = ">=3.11.14,<3.14"
rich = ">=14.3.2,<15"
interegular = ">=0.3.3,<0.4"
sympy = ">=1.14.0,<2"
altair = ">=6.0.0,<7"
tempita = ">=0.6.0,<0.7"
pytest = ">=9.0.2,<10"

dynare-preprocessor-pylib = ">=0.0.0.dev1,<0.0.0.dev2"
dolang = ">=0.0.21,<0.0.22"
numpy = ">=2.4.2,<3" # Compatibility with notebook.link scipy
scipy = ">=1.17.0,<2"
pandas = ">=3.0.0,<4"
typing_extensions = ">=4.15.0,<5"
plotly = ">=6.5.2,<7"
black = ">=26.1.0,<27"
pathspec = ">=1.0.4,<2"
ripgrep = ">=15.1.0,<16"

[package.build]
backend = { name = "pixi-build-python", version = ">=0.4.0" }

[package.host-dependencies] 
hatchling = "==1.26.3"
python = "<3.14,>=3.11"

[feature.test.dependencies]
pytest = ">=9.0.2,<10"
coverage = ">=7.13.4,<8"
pytest-cov = ">=7.0.0,<8"

[feature.test.tasks]
test = "pytest"
durations = "pytest --durations=0 -vv"
cov = "pytest --cov=./ --cov-report=xml"

[feature.lint.dependencies]
mypy = ">=1.19.1,<2"
pandas-stubs = ">=3.0.0.260204,<4"
scipy-stubs = ">=1.17.0.2,<2"
types-mock = ">=5.2.0.20250924,<6"
types-pyyaml = ">=6.0.12.20250915,<7"
black = ">=26.1.0,<27"

[feature.lint.tasks]
typecheck = "mypy src --ignore-missing-imports"
black = "black src tests"
ci-qc = "black src tests --check"

[feature.gui.dependencies]
mock = ">=5.2.0,<6"
ipyvuetify = ">=1.11.3,<2"
solara = ">=1.57.1,<2"
solara-ui = ">=1.57.1,<2"
solara-server = ">=1.57.1,<2"
anywidget = ">=0.9.21,<0.10"

[feature.gui.tasks]
solara = "solara run examples/rbc_gui.py"

[feature.jupyter.dependencies]
jupyterlab = ">=4.5.4,<5"
ipykernel = ">=7.2.0,<8"
matplotlib = ">=3.10.8,<4"
notebook = ">=7.5.3,<8"

[feature.jupyter.tasks]
notebook = "ipython kernel install --name $PIXI_ENVIRONMENT_NAME --user && jupyter notebook"
jlab = "ipython kernel install --name $PIXI_ENVIRONMENT_NAME --user && jupyter lab"
ipython = "ipython"

[feature.docs.dependencies]
mkdocs = ">=1.6.1,<2"
mkdocstrings-python = ">=2.0.2,<3"
mkdocs-material = ">=9.7.1,<10"
pymdown-extensions = ">=10.21.1,<11"
python-markdown-math = ">=0.9,<0.10"

[feature.docs.tasks]
docs = "mkdocs serve"

[feature.py311.dependencies]
python = ">=3.11.14,<3.12"

[feature.py312.dependencies]
python = ">=3.12.12,<3.13"

[feature.py313.dependencies]
python = ">=3.13.12,<3.14"

# [feature.experimental.dependencies]
# sympy = "*"
# python-symengine = "*"
# jax = "*"

[environments]
test = ["test"]
prod = ["jupyter"]
solara = ["gui"]
dev = ["test", "lint", "jupyter", "docs"]
py311 = ["test", "lint", "py311"]
py312 = ["test", "lint", "py312"]
py313 = ["test", "lint", "py313"]
