[workspace]
authors = ["Pablo Winant <pablo.winant@gmail.com>","Ousema Bouaneni <ousema.bouaneni@polytechnique.edu>"]
description = "Macroeconomic model solver"
channels = ["conda-forge"]
preview = ["pixi-build"]
platforms = ["linux-64"]

[package]
name = "dyno"
version = "0.1.5.dev6"

[dependencies]
dyno = { path = "." }

[package.run-dependencies]
dynare-preprocessor-pylib = "==0.0.0.dev1"
dolang = ">=0.0.20"
numpy = ">=2.0.0, <2.3.0" # Compatibility with notebook.link scipy
scipy = ">=1.12.0"
pandas = ">=2.2.2"
typing_extensions = ">=4.12.0"
plotly = ">=5.18.0"

[package.build]
backend = { name = "pixi-build-python", version = "==0.3.2" }

[package.host-dependencies] 
hatchling = "==1.26.3"
python = "<3.14,>=3.10"

[feature.test.dependencies]
pytest = ">=8.3.3"
coverage = ">=6.4.4"
pytest-cov = ">=4.0.0"

[feature.test.tasks]
test = "pytest"
durations = "pytest --durations=0 -vv"
cov = "pytest --cov=./ --cov-report=xml"

[feature.lint.dependencies]
mypy = ">=1.0.0"
pandas-stubs = ">=2.2.2"
scipy-stubs = ">=1.12.0"
types-mock = ">=5.0.0.0"
types-pyyaml = ">=6.0.12"
black = ">=24.10.0"

[feature.lint.tasks]
typecheck = "mypy dyno --ignore-missing-imports"
black = "black"
ci-qc = "black . --check"

[feature.gui.dependencies]
mock = ">=5.1.0"
ipyvuetify = ">=1.8.10"
solara = ">=1.34.0"
solara-ui = ">=1.34.0"
solara-server = ">=1.34.0"
anywidget = ">=0.9.18,<0.10"

[feature.gui.tasks]
solara = "solara run examples/rbc_gui.py"

[feature.jupyter.dependencies]
jupyterlab = ">=4.0.9"
ipykernel = ">=6.29.0"
matplotlib = ">=3.10.0"
notebook = ">=7.4.5,<8"

[feature.jupyter.tasks]
notebook = "ipython kernel install --name $PIXI_ENVIRONMENT_NAME --user && jupyter notebook"
jlab = "ipython kernel install --name $PIXI_ENVIRONMENT_NAME --user && jupyter lab"
ipython = "ipython"

[feature.docs.dependencies]
mkdocs = ">=1.6.1"
mkdocstrings-python = ">=1.16.0"
mkdocs-material = ">=9.6.0"
pymdown-extensions = ">=10.12"
python-markdown-math = ">=0.8"

[feature.docs.tasks]
docs = "mkdocs serve"

[feature.py310.dependencies]
python = "3.10.*"

[feature.py311.dependencies]
python = "3.11.*"

[feature.py312.dependencies]
python = "3.12.*"

[feature.py313.dependencies]
python = "3.13.*"

[environments]
test = ["test"]
prod = ["jupyter"]
solara = ["gui"]
dev = ["test", "gui", "lint", "jupyter", "docs"]
py310 = ["test", "lint", "py310"]
py311 = ["test", "lint", "py311"]
py312 = ["test", "lint", "py312"]
py313 = ["test", "lint", "py313"]
