[project]
name = "dyno"
version = "0.1.0"
description = "Add a short description here"
authors = ["Pablo Winant <pablo.winant@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
dolang = "0.0.20.*"
scipy = "1.11.4.*"
bqplot = "0.12.42.*"
xarray = "2023.11.0.*"
reacton = "1.8.1.*"
voila = "0.5.5.*"
voici = "0.5.0.*"
jupyterlab = "4.0.9.*"
ipyvuetify = "1.8.10.*"
plotly = "5.18.0.*"
mock = "5.1.0.*"
mkdocs = "1.6.0.*"
solara = "1.34.0.*"
solara-ui = "1.34.0.*"
solara-server = "1.34.0.*"
