[tool.poetry]
name = "dynopy"
version = "0.1.3"
description = ""
authors = ["Pablo Winant <pablo.winant@gmail.com>"]
readme = "README.md"
packages = [{include = "dyno"}]


[tool.poetry.dependencies]
python = ">=3.10, <3.13"
dolang = "^0.0.21"
numpy = "^2.0.0"
scipy = "^1.12.0"
pandas = "^2.2.2"
black = "^24.10.0"

[tool.poetry.dev-dependencies]
pytest = "^8.3.3"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
