[tool.poetry]
name = "dynopy"
version = "0.1.2"
description = ""
authors = ["Pablo Winant <pablo.winant@gmail.com>"]
readme = "README.md"
packages = [{include = "dyno"}]


[tool.poetry.dependencies]
python = ">=3.10, <3.12"
dolang = "^0.0.20"
numpy = "^1.20"
scipy = "^1.12.0"
pandas = "^2.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
