[project]
name = "dyno"
version = "0.1.5"
requires-python = ">= 3.10,<3.13"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

# [tool.poetry]
# name = "dynopy"
# version = "0.1.4"
# description = ""
# authors = ["Pablo Winant <pablo.winant@gmail.com>"]
# readme = "README.md"
# packages = [{include = "dyno"}]


# [tool.poetry.dependencies]
# python = ">=3.10, <3.13"
# dolang = "^0.0.21"
# numpy = "^2.0.0"
# scipy = "^1.12.0"
# pandas = "^2.2.2"
# typing_extensions = "^4.12.0"

# [tool.poetry.group.dev.dependencies]
# mypy = "^1.0.0"
# pandas-stubs = "^2.2.2"
# scipy-stubs = "^1.12.0"
# types-mock = "^5.0.0.0"
# types-PyYAML = "^6.0.12"
# pytest = "^8.3.3"
# black = "^24.10.0"
# mkdocs = "^1.6.1"
# mkdocstrings-python = "^1.16.0"
# mkdocs-material = "^9.6.0"
# coverage = "^6.4.4"
# pytest-cov = "^4.0.0"
# pymdown-extensions = "^10.12"
# python-markdown-math = "^0.8"

# [build-system]
# requires = ["poetry-core"]
# build-backend = "poetry.core.masonry.api"