[tool.poetry]
name = "dyno"
version = "0.1.0"
description = ""
authors = ["Pablo Winant <pablo.winant@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10, <3.12"
dolang = "^0.0.20"
numpy = "^1.26.2"
xarray = "^2023.12.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
